# Site settings
title: Chorok's Lair
description: "Chorok Daddy's Blog"
url: "https://chorok-daddy.github.io"
author:
  name: "Chorok daddy"
  email: "chorok.daddy@gmail.com"
  url: "https://chorok-daddy.github.io"

# Build settings
baseurl: https://chorok-daddy.github.io # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

social_links:
    github: chorok-daddy
    #linkedin: 
    #twitter:

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
